---

- name: "links: Create directories for links"
  file:
    state: directory
    dest: "{{ item.dest|dirname }}"
  loop: "{{ ar_links }}"

- name: "links: Create links"
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force|default(false) }}"
  loop: "{{ ar_links }}"

# EOF
...
