---

- name: "Declare ar_owner when undefined"
  set_fact:
    ar_owner: "{{ ansible_user_id }}"
  when: ar_owner is undefined

- name: "Default vars for {{ ansible_os_family }}
                          {{ ansible_distribution }}
                          {{ ansible_distribution_release }}"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
        - defaults.yml
      paths: "{{ role_path }}/vars/defaults"

- name: "Custom vars for {{ ansible_os_family }}
                         {{ ansible_distribution }}
                         {{ ansible_distribution_release }}"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
        - defaults.yml
      paths: "{{ role_path }}/vars"

# EOF
...
